#!/bin/bash

case "$1" in
    "remove" | "purge" | "abort-install" | "disappear")
        rm -f /etc/nginx/sites-enabled/10-card_proxy_keykeeper2
        service nginx restart
        service card_proxy_keykeeper2 stop

        update-rc.d card_proxy_keykeeper2 remove
        ;;

    "upgrade" | "failed-upgrade" | "abort-upgrade")
        ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

exit 0

